package com.csec.goat.controller;

import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

/**
 * Created by cryin
 * Date:2018/10/5
 * Copyright by Code Security Group.
 * Description:信息泄露漏洞demo
 */
@RestController
public class InfoDisclosureController {
    @RequestMapping(value="/readme.html",method= RequestMethod.GET)
    public String urlgo(ModelMap modelMap, HttpServletRequest request, HttpServletResponse response) throws IOException {
        String test1=request.getParameter("test1");
        String id=request.getParameter("id");

        return "Employee information：lizhicheng@csec.com 1988.10.12";
    }

    @RequestMapping(value="/wafid.html",method= RequestMethod.GET)
    public String wafid(ModelMap modelMap, HttpServletRequest request, HttpServletResponse response) throws IOException {

        return "This error was generated by Mod_Security";
    }
}
